namespace Llyn.Core;

public sealed record LRig(
    LVault LRigVault,
    LRigKeeping LRigKeeping,
    LSettingsVault LRigSettings,
    LAuditVault LRigAudit,
    LPostureVault LRigPosture,
    LRigAsset LRigAsset,
    LEntryVault LRigEntries,
    LEntryQueryVault LRigEntryQuery,
    LRigLexicon LRigLexicon,
    LRigDraft LRigDraft,
    LRigCitation LRigCitation,
    LRigSound LRigSound,
    LRigSentence LRigSentence,
    LRigContext LRigContext,
    LRigSource LRigSource,
    LOutpost LRigOutpost,
    LLanguageVault LRigLanguages,
    LPress LRigPress,
    LWarrant LRigWarrant,
    LUsher LRigUsher,
    LPhonograph LRigPhonograph,
    LTrail LRigTrail,
    LClock LRigClock,
    int LRigProcess,
    string LRigWorkspace);
