<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Llyn.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Llyn.Core\Llyn.Core.csproj" />
    <ProjectReference Include="..\Llyn.Application\Llyn.Application.csproj" />
    <ProjectReference Include="..\Llyn.ShellEngine\Llyn.ShellEngine.csproj" />
  </ItemGroup>
</Project>
