namespace Llyn.Core;

public sealed record LPortraitLabel(
    string LPortraitLabelUnknown,
    string LPortraitLabelMeaning,
    string LPortraitLabelMeanings,
    string LPortraitLabelCollocation,
    string LPortraitLabelCollocations,
    string LPortraitLabelIncoming,
    string LPortraitLabelNote,
    string LPortraitLabelForm,
    string LPortraitLabelParadigm,
    string LPortraitLabelFrequency,
    string LPortraitLabelGlyph,
    string LPortraitLabelScript,
    string LPortraitLabelFanqie,
    string LPortraitLabelExample,
    string LPortraitLabelGloss,
    string LPortraitLabelSource,
    string LPortraitLabelMention,
    string LPortraitLabelEtymology,
    string LPortraitLabelSituation,
    string LPortraitLabelRegister,
    string LPortraitLabelTranslation,
    string LPortraitLabelTag);
