namespace Llyn.Core;

public sealed record LPortraitLabel(
    string LPortraitLabelUnknown,
    string LPortraitLabelMeaning,
    string LPortraitLabelMeanings,
    string LPortraitLabelCollocation,
    string LPortraitLabelCollocations,
    string LPortraitLabelIncoming,
    string LPortraitLabelNote,
    string LPortraitLabelForm,
    string LPortraitLabelParadigm,
    string LPortraitLabelFrequency,
    string LPortraitLabelGlyph,
    string LPortraitLabelScript,
    string LPortraitLabelFanqie,
    string LPortraitLabelExample,
    string LPortraitLabelGloss,
    string LPortraitLabelSource,
    string LPortraitLabelMention,
    string LPortraitLabelSituation,
    string LPortraitLabelRegister,
    string LPortraitLabelTranslation,
    string LPortraitLabelTag)
{
    public static LPortraitLabel LPortraitLabelDefault { get; } = new(
        "Unknown",
        "Meaning",
        "Meanings",
        "Collocation",
        "Collocations",
        "Links here",
        "Note",
        "Forms",
        "Paradigm",
        "Frequency",
        "Characters",
        "Character forms",
        "Rime books",
        "Example",
        "Gloss",
        "Source",
        "Mentions",
        "Situations",
        "Registers",
        "Translations",
        "Tags");
}
