// Generated file. Do not edit by hand: every line is overwritten when it is rebuilt.
//
// AUDITNAMES GENERATION 21 - name registry for Llyn.
// One of the two generated files in the convention-test project. Together they carry the
// registered bases, verbs and exemptions and nothing else; every audit setting is hand-written
// tracked test code and must never be added here.
//
// Order: regenerate it first, then run the convention tests. The tests compile against this file as
// it is on disk, so a newly registered name is invisible to them until it is regenerated.

namespace Convention.Tests;

internal static class TAuditVerbRegistry
{
    // AUDIT:SIDECAR:VERBS:START
    public static readonly string[] TAuditVerbs =
    [
        "Absorb",
        "Accept",
        "Add",
        "Adjust",
        "Advance",
        "Append",
        "Apply",
        "Attach",
        "Build",
        "Cancel",
        "Change",
        "Check",
        "Clamp",
        "Clear",
        "Clone",
        "Close",
        "Commit",
        "Confirm",
        "Consult",
        "Copy",
        "Create",
        "Defer",
        "Delete",
        "Describe",
        "Detach",
        "Dispatch",
        "Dispose",
        "Divide",
        "Draw",
        "Exist",
        "Export",
        "Find",
        "Finish",
        "Format",
        "Handle",
        "Hide",
        "Hook",
        "Import",
        "Insert",
        "Interrupt",
        "Introduce",
        "Load",
        "Match",
        "Move",
        "Normalize",
        "Observe",
        "Open",
        "Parse",
        "Pause",
        "Persist",
        "Place",
        "Play",
        "Prepare",
        "Print",
        "Propagate",
        "Publish",
        "Raise",
        "Read",
        "Rebuild",
        "Record",
        "Redo",
        "Refine",
        "Remove",
        "Reset",
        "Resolve",
        "Resonate",
        "Restore",
        "Resume",
        "Retreat",
        "Run",
        "Save",
        "Scan",
        "Scroll",
        "Seek",
        "Select",
        "Send",
        "Set",
        "Settle",
        "Shorten",
        "Show",
        "Sort",
        "Spread",
        "Start",
        "Stop",
        "Suspend",
        "Sweep",
        "Sync",
        "Teardown",
        "Tick",
        "Toggle",
        "Undo",
        "Update",
        "Validate",
        "Zoom",
    ];
    // AUDIT:SIDECAR:VERBS:END
}
