namespace Convention.Tests;

internal static class TAuditBorderSetting
{
    public const int TAuditGeneration = 19;
    public const string TAuditBorderHost = "Llyn.Host";

    public static readonly IReadOnlyDictionary<string, string[]> TAuditBorderNeighbour =
        new Dictionary<string, string[]>
        {
            ["Llyn.Core"] = [],
            ["Llyn.Application"] = ["Llyn.Core"],
            ["Llyn.ShellEngine"] = ["Llyn.Application"],
            ["Llyn.Conduct"] = ["Llyn.ShellEngine"],
            ["Llyn.UIDeportment"] = ["Llyn.Conduct"],
            ["Llyn.UIVeneer"] = ["Llyn.UIDeportment"],
            ["Llyn.UIDemeanor"] = ["Llyn.Conduct"],
            ["Llyn.UITerminal"] = ["Llyn.UIDemeanor"],
            ["Llyn.Infrastructure"] = ["Llyn.Core"],
            ["Llyn.Core.Windows"] = ["Llyn.Core"],
            ["Llyn.UIDeportment.Capsule"] = [],
        };

    public static readonly IReadOnlyDictionary<string, string> TAuditBorderCapsule = new Dictionary<string, string>
    {
        ["Llyn.UIDeportment"] = "Llyn.UIDeportment.Capsule",
    };

    public static readonly string[] TAuditBorderCut =
    [
        "Llyn.UIVeneer",
        "Llyn.UIDeportment",
        "Llyn.UIDeportment.Capsule",
        "Llyn.UIDemeanor",
        "Llyn.UITerminal",
    ];

    public static readonly IReadOnlyDictionary<string, string[]> TAuditBorderOffer = new Dictionary<string, string[]>
    {
        ["Llyn.Conduct>Llyn.ShellEngine"] =
        [
            "LDraftPort",
            "LEntryPort",
            "LPhonologyPort",
            "LSettingsPort",
            "LMediaPort",
            "LPortraitPort",
            "LTenure",
            "LVista",
            "LForay",
            "LPosture",
            "LQuill",
            "LEasel",
            "LQuillChip",
            "LQuillCard",
            "LQuillSituation",
            "LQuillReflex",
        ],
        ["Llyn.UIDeportment>Llyn.Conduct"] =
        [
            "LDisplay",
            "LDisplaySound",
            "CSentence",
            "CSentenceFrame",
            "CTranscript",
            "CSCoinage",
            "CSCustoms",
            "CSCustomsMode",
            "CSCustomsRow",
            "CCatalogOrder",
            "CCatalogFilter",
            "CSubject",
            "CBulletin",
            "CDraft",
            "CHarvestStep",
            "CLookupStep",
            "CRecording",
            "CClipRoll",
            "CClipItem",
            "CClipReading",
            "CNotationRoll",
            "CNotationItem",
            "CNotationReading",
            "CFanqieGroup",
            "CFanqieRow",
            "CScriptGroup",
            "CScriptImage",
            "CParadigmSlot",
            "CAnchorRow",
            "CAnchor",
            "CFrequency",
            "CVistaRow",
            "CCatalogSituation",
            "CCatalogReference",
            "CCatalogPronunciation",
            "CStem",
            "CStemPage",
            "CDiwei",
            "CDiweiPage",
            "CDiweiSection",
            "CDiweiLine",
            "CTally",
            "CTallyMark",
            "CStateValue",
            "CStateWording",
            "CRegister",
            "CTag",
            "CSentenceOrder",
            "CTranslationTarget",
            "CColophon",
            "CEntryDraft",
            "CTranscriptionDraft",
            "CReflexDraft",
            "CEtymologyDraft",
            "CCardDraft",
            "CSentenceDraft",
            "CExampleDraft",
            "CGlossDraft",
            "CSituationDraft",
            "CScenario",
            "CScenarioLine",
            "CSituation",
            "CRegisterDraft",
            "CTagDraft",
            "CImageDraft",
            "CVideoDraft",
            "CPostureState",
            "CWindowState",
            "CLayout",
            "CSettings",
            "CWorkspaceState",
            "CEstablishment",
            "CEnsignRow",
            "CEnsignSheet",
            "CFont",
            "CFontRole",
            "CMentionMark",
            "CMentionPiece",
            "CMentionLabel",
            "CMeaning",
            "CMarkdownBlock",
            "CMarkdownSpan",
            "CCatalogTag",
            "CCatalogRegister",
            "CPortraitChoice",
            "CPortraitMedium",
            "CPressTicket",
            "CPressSide",
            "CPressInk",
            "CMarkupEntry",
            "CMarkupOmission",
            "CExample",
            "CMentionOffer",
            "CMentionSense",
            "CMention",
            "CRespelling",
            "CRespellingMark",
            "CVariety",
            "CAccent",
            "CReflex",
            "CReflexHead",
            "CReflexTyped",
            "CAccentTyped",
            "CScheme",
            "CCatalogExample",
            "CCatalogAuthor",
            "CVita",
            "CFellow",
            "CUsage",
            "CAuthor",
            "CAuthorRow",
            "CReference",
            "CReferenceKind",
            "CAtelier",
            "CEnvoy",
            "CCatalog",
            "CLedger",
            "CLedgerPage",
            "CLedgerState",
            "CLedgerShown",
            "CLedgerNotice",
            "CWorkspace",
            "CCardSpeech",
            "CCardField",
            "CCardList",
            "CImage",
            "CVideo",
            "CMarker",
            "CCategory",
            "CCategoryRow",
            "CProspect",
            "CSlate",
            "CSlateRow",
            "CProffer",
            "CProfferRow",
            "CDesk",
            "CEditor",
            "CNavigation",
            "CNavigationState",
            "CSession",
            "CErrand",
            "LVigil",
            "CCard",
            "CSounding",
            "CSoundingAnchor",
            "CSoundingScript",
            "CSoundingFanqie",
            "CPanel",
            "CAtlas",
            "COeuvre",
            "CWing",
            "CVoyageState",
            "CAnthology",
            "CEsteem",
            "CTimbre",
            "CPlayback",
            "CPlaywright",
            "CPortrait",
            "CCorpus",
            "CQuotation",
            "CMembership",
            "CCohort",
            "CFavorite",
            "CFootnote",
            "CGuild",
            "CGuildRoll",
            "CImprint",
            "CByline",
            "CLantern",
            "CLibrary",
            "COccurrence",
            "CRepertoire",
            "CShelf",
            "CShelfRoll",
            "CTaxonomy",
            "CTenor",
            "CPhonology",
            "CXiesheng",
            "CYunjing",
            "CCompassPart",
            "CCompassRow",
            "CDisplay",
            "CLectern",
            "CGrasp",
            "CLecternAccent",
            "CLecternCard",
            "CLeaf",
            "CLeafChip",
            "CLeafLine",
            "CLecternEtymology",
            "CDisplaySound",
            "CLecternGlyph",
            "CGlyphCell",
            "CLecternReflex",
            "CLecternAnchor",
            "CLecternFanqie",
            "CLecternScript",
            "CLecternParadigm",
            "CLecternPlayback",
            "CTimbrePlayback",
            "CTimbreAccent",
            "CTimbreReflex",
            "CTimbreGlyph",
            "CTranscription",
            "CTranscriptionSheet",
            "CTranscriptionRow",
            "CReflexField",
            "CContour",
            "CArticulation",
            "CScreen",
        ],
        ["Llyn.UIDemeanor>Llyn.Conduct"] =
        [
            "LDisplay",
            "LDisplaySound",
            "CSentence",
            "CSentenceFrame",
            "CSCoinage",
            "CSCustoms",
            "CSCustomsMode",
            "CSCustomsRow",
            "CCatalogOrder",
            "CCatalogFilter",
            "CSubject",
            "CBulletin",
            "CDraft",
            "CHarvestStep",
            "CLookupStep",
            "CRecording",
            "CCandidate",
            "CFanqieGroup",
            "CFanqieRow",
            "CScriptGroup",
            "CScriptImage",
            "CParadigmSlot",
            "CAnchorRow",
            "CFrequency",
            "CVistaRow",
            "CCatalogSituation",
            "CCatalogReference",
            "CCatalogPronunciation",
            "CStem",
            "CStemPage",
            "CDiwei",
            "CDiweiPage",
            "CDiweiSection",
            "CDiweiLine",
            "CTally",
            "CTallyMark",
            "CStateValue",
            "CRegister",
            "CTag",
            "CSentenceOrder",
            "CTranslationTarget",
            "CColophon",
            "CEntryDraft",
            "CTranscriptionDraft",
            "CReflexDraft",
            "CEtymologyDraft",
            "CCardDraft",
            "CSentenceDraft",
            "CExampleDraft",
            "CGlossDraft",
            "CSituationDraft",
            "CRegisterDraft",
            "CTagDraft",
            "CImageDraft",
            "CVideoDraft",
            "CPostureState",
            "CWindowState",
            "CLayout",
            "CSettings",
            "CWorkspaceState",
            "CEstablishment",
            "CEnsignRow",
            "CFont",
            "CFontRole",
            "CMentionMark",
            "CMentionPiece",
            "CMentionLabel",
            "CMeaning",
            "CMarkdownBlock",
            "CMarkdownSpan",
            "CCatalogTag",
            "CCatalogRegister",
            "CPortraitMedium",
            "CPressTicket",
            "CPressSide",
            "CPressInk",
            "CMarkupEntry",
            "CMarkupOmission",
            "CExample",
            "CMention",
            "CRespelling",
            "CRespellingMark",
            "CCatalogExample",
            "CCatalogAuthor",
            "CVita",
            "CFellow",
            "CUsage",
            "CAuthor",
            "CAuthorRow",
            "CReference",
        ],
    };

    public static readonly IReadOnlyDictionary<string, string[]> TAuditUnsealingPrefix =
        new Dictionary<string, string[]>
        {
            ["Llyn.UIDeportment"] = ["L"],
        };

    public static readonly IReadOnlyDictionary<string, int> TAuditBorderCeiling = new Dictionary<string, int>
    {
        ["Leaking:Llyn.UIDemeanor>Llyn.Core"] = 0,
        ["Leaking:Llyn.UIDemeanor>Llyn.ShellEngine"] = 1,
        ["Leaking:Llyn.UIDeportment>Llyn.Core"] = 0,
        ["Leaking:Llyn.UIDeportment>Llyn.ShellEngine"] = 1,
        ["Leapfrogging:Llyn.Conduct>Llyn.Core"] = 0,
        ["Leapfrogging:Llyn.ShellEngine>Llyn.Core"] = 0,
        ["Undercutting:Llyn.UIDeportment>Llyn.Application"] = 0,
        ["Undercutting:Llyn.UIDeportment>Llyn.Core"] = 0,
        ["Undercutting:Llyn.UIDeportment>Llyn.ShellEngine"] = 0,
        ["Unsealing:Llyn.UIDeportment>Llyn.Application"] = 0,
        ["Unsealing:Llyn.UIDeportment>Llyn.Core"] = 0,
        ["Unsealing:Llyn.UIDeportment>Llyn.ShellEngine"] = 0,
    };

    public static readonly string[] TAuditBorderExempt = [];
}
