namespace Convention.Tests;

internal static class TAuditChainSetting
{
    public const int TAuditGeneration = 16;
    public const string TAuditChainHost = "Llyn.Host";

    public static readonly IReadOnlyDictionary<string, string[]> TAuditChainReach = new Dictionary<string, string[]>
    {
        ["Llyn.Core"] = [],
        ["Llyn.Application"] = ["Llyn.Core"],
        ["Llyn.ShellEngine"] = ["Llyn.Application"],
        ["Llyn.Conduct"] = ["Llyn.ShellEngine"],
        ["Llyn.UIDeportment"] = ["Llyn.Conduct"],
        ["Llyn.UIVeneer"] = ["Llyn.UIDeportment"],
        ["Llyn.UIDemeanor"] = ["Llyn.Conduct"],
        ["Llyn.UITerminal"] = ["Llyn.UIDemeanor"],
        ["Llyn.Infrastructure"] = ["Llyn.Core"],
        ["Llyn.Core.Windows"] = ["Llyn.Core"],
        ["Llyn.UIDeportment.Capsule"] = [],
    };

    public static readonly IReadOnlyDictionary<string, string> TAuditChainCapsule = new Dictionary<string, string>
    {
        ["Llyn.UIDeportment"] = "Llyn.UIDeportment.Capsule",
    };

    public static readonly string[] TAuditChainCut =
    [
        "Llyn.UIVeneer",
        "Llyn.UIDeportment",
        "Llyn.UIDeportment.Capsule",
        "Llyn.UIDemeanor",
        "Llyn.UITerminal",
    ];

    public static readonly IReadOnlyDictionary<string, string[]> TAuditChainSurface = new Dictionary<string, string[]>
    {
        ["Llyn.Conduct>Llyn.ShellEngine"] =
        [
            "LDraftPort",
            "LEntryPort",
            "LPhonologyPort",
            "LSettingsPort",
            "LMediaPort",
            "LPortraitPort",
            "LTenure",
            "LVista",
            "LForay",
            "LPosture",
            "LQuill",
            "LEasel",
        ],
        ["Llyn.UIDeportment>Llyn.Conduct"] =
        [
            "LDisplay",
            "LDisplaySound",
            "LDisplayStamp",
            "CSentence",
            "CSentenceFrame",
            "CSCoinage",
            "CSCustoms",
            "CSCustomsMode",
            "CSCustomsRow",
            "CCatalogOrder",
            "CCatalogFilter",
            "CSubject",
            "CBulletin",
            "CDraft",
            "CMentionDraft",
            "CHarvestStep",
            "CLookupStep",
            "CRecording",
            "CCandidate",
            "CFanqieGroup",
            "CFanqieRow",
            "CScriptGroup",
            "CScriptImage",
            "CParadigmSlot",
            "CAnchorRow",
            "CFrequency",
            "CVistaRow",
            "CCatalogSituation",
            "CCatalogReference",
            "CCatalogPronunciation",
            "CStem",
            "CStemPage",
            "CDiwei",
            "CDiweiPage",
            "CDiweiSection",
            "CDiweiLine",
            "CTally",
            "CTallyMark",
            "CStateValue",
            "CRegister",
            "CTag",
            "CSentenceOrder",
            "CTranslationTarget",
            "CColophon",
            "CEntryDraft",
            "CPronunciationDraft",
            "CSpeechDraft",
            "CTranscriptionDraft",
            "CReflexDraft",
            "CEtymologyDraft",
            "CCardDraft",
            "CSentenceDraft",
            "CExampleDraft",
            "CGlossDraft",
            "CSituationDraft",
            "CRegisterDraft",
            "CTagDraft",
            "CImageDraft",
            "CVideoDraft",
            "CPostureState",
            "CWindowState",
            "CLayout",
            "CSettings",
            "CWorkspaceState",
            "CEstablishment",
            "CEnsignRow",
            "CFont",
            "CFontRole",
            "CGlyph",
            "CReflexRule",
            "CMentionMark",
            "CMentionPiece",
            "CMentionLabel",
            "CSpeechValue",
            "CMeaning",
            "CMarkdownBlock",
            "CMarkdownSpan",
            "CCatalogTag",
            "CCatalogRegister",
            "CPortraitLabel",
            "CPortraitLegend",
            "CPortraitMedium",
            "CPressTicket",
            "CPressSide",
            "CPressInk",
            "CMarkupEntry",
            "CMarkupOmission",
            "CExample",
            "CMentionResult",
            "CMention",
            "CMarkdown",
            "CRespelling",
            "CRespellingMark",
            "CCatalogExample",
            "CCatalogAuthor",
            "CVita",
            "CFellow",
            "CUsage",
            "CCitationRow",
            "CAuthor",
            "CAuthorRow",
            "CImprint",
            "CAtelier",
            "CEnvoy",
            "CCatalog",
            "CLedger",
            "CLedgerPage",
            "CLedgerState",
            "CDesk",
            "CEditor",
            "CNavigation",
            "CSession",
            "CErrand",
            "LVigil",
            "CCard",
            "CFolio",
            "CSounding",
            "CPanel",
            "CAtlas",
            "COeuvre",
            "CWing",
            "CVoyage",
            "CVoyageState",
            "CAnthology",
            "CEsteem",
            "CTimbre",
            "CPortrait",
        ],
        ["Llyn.UIDemeanor>Llyn.Conduct"] =
        [
            "LDisplay",
            "LDisplaySound",
            "LDisplayStamp",
            "CSentence",
            "CSentenceFrame",
            "CSCoinage",
            "CSCustoms",
            "CSCustomsMode",
            "CSCustomsRow",
            "CCatalogOrder",
            "CCatalogFilter",
            "CSubject",
            "CBulletin",
            "CDraft",
            "CMentionDraft",
            "CHarvestStep",
            "CLookupStep",
            "CRecording",
            "CCandidate",
            "CFanqieGroup",
            "CFanqieRow",
            "CScriptGroup",
            "CScriptImage",
            "CParadigmSlot",
            "CAnchorRow",
            "CFrequency",
            "CVistaRow",
            "CCatalogSituation",
            "CCatalogReference",
            "CCatalogPronunciation",
            "CStem",
            "CStemPage",
            "CDiwei",
            "CDiweiPage",
            "CDiweiSection",
            "CDiweiLine",
            "CTally",
            "CTallyMark",
            "CStateValue",
            "CRegister",
            "CTag",
            "CSentenceOrder",
            "CTranslationTarget",
            "CColophon",
            "CEntryDraft",
            "CPronunciationDraft",
            "CSpeechDraft",
            "CTranscriptionDraft",
            "CReflexDraft",
            "CEtymologyDraft",
            "CCardDraft",
            "CSentenceDraft",
            "CExampleDraft",
            "CGlossDraft",
            "CSituationDraft",
            "CRegisterDraft",
            "CTagDraft",
            "CImageDraft",
            "CVideoDraft",
            "CPostureState",
            "CWindowState",
            "CLayout",
            "CSettings",
            "CWorkspaceState",
            "CEstablishment",
            "CEnsignRow",
            "CFont",
            "CFontRole",
            "CGlyph",
            "CReflexRule",
            "CMentionMark",
            "CMentionPiece",
            "CMentionLabel",
            "CSpeechValue",
            "CMeaning",
            "CMarkdownBlock",
            "CMarkdownSpan",
            "CCatalogTag",
            "CCatalogRegister",
            "CPortraitLabel",
            "CPortraitLegend",
            "CPortraitMedium",
            "CPressTicket",
            "CPressSide",
            "CPressInk",
            "CMarkupEntry",
            "CMarkupOmission",
            "CExample",
            "CMentionResult",
            "CMention",
            "CMarkdown",
            "CRespelling",
            "CRespellingMark",
            "CCatalogExample",
            "CCatalogAuthor",
            "CVita",
            "CFellow",
            "CUsage",
            "CCitationRow",
            "CAuthor",
            "CAuthorRow",
            "CImprint",
        ],
    };

    public static readonly IReadOnlyDictionary<string, string[]> TAuditSealPrefix = new Dictionary<string, string[]>
    {
        ["Llyn.UIDeportment"] = ["L"],
    };

    public static readonly IReadOnlyDictionary<string, int> TAuditChainFloor = new Dictionary<string, int>
    {
        ["Llyn.Application"] = 91,
    };

    public static readonly IReadOnlyDictionary<string, string[]> TAuditChainStray = new Dictionary<string, string[]>
    {
        ["Llyn.Core"] = [@"^LRequest"],
    };

    public static readonly IReadOnlyDictionary<string, string[]> TAuditChainBanned = new Dictionary<string, string[]>
    {
        ["src/Llyn.ShellEngine"] = ["LVaultSessionStart"],
    };

    public static readonly IReadOnlyDictionary<string, int> TAuditChainCeiling = new Dictionary<string, int>
    {
        ["cross:Llyn.UIDeportment>Llyn.Application"] = 89,
        ["cross:Llyn.UIDeportment>Llyn.Core"] = 354,
        ["cross:Llyn.UIDeportment>Llyn.ShellEngine"] = 362,
        ["expose:Llyn.UIDemeanor>Llyn.Core"] = 23,
        ["expose:Llyn.UIDemeanor>Llyn.ShellEngine"] = 1,
        ["expose:Llyn.UIDeportment>Llyn.Core"] = 23,
        ["expose:Llyn.UIDeportment>Llyn.ShellEngine"] = 1,
        ["reach:Llyn.Conduct>Llyn.Core"] = 1,
        ["reach:Llyn.ShellEngine>Llyn.Core"] = 15,
        ["seal:Llyn.UIDeportment>Llyn.Application"] = 0,
        ["seal:Llyn.UIDeportment>Llyn.Core"] = 3,
        ["seal:Llyn.UIDeportment>Llyn.ShellEngine"] = 0,
    };

    public static readonly string[] TAuditChainWaiver = [];
}
