<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>CA1416</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Llyn.Internal" />
    <InternalsVisibleTo Include="Llyn.Windows" />
    <InternalsVisibleTo Include="Llyn" />
    <InternalsVisibleTo Include="Llyn.UIDeportment" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Llyn.ShellEngine\Llyn.ShellEngine.csproj" />
  </ItemGroup>
</Project>
