using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Animation;

namespace Llyn.UIDeportment;

internal static class PLookSound
{
    internal static readonly IReadOnlyList<PLook.PLookSetter> PLookSoundState =
    [
        new("Theme.Pronunciation.Flag", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Pronunciation.Label", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Pronunciation.Surface", "Hover", "PAccentShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Pronunciation.Surface", "Hover", "PAccentShelf", UIElement.IsHitTestVisibleProperty, true),
        new("Theme.Pronunciation.Surface", "Focus", "PAccentShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Pronunciation.Surface", "Focus", "PAccentShelf", UIElement.IsHitTestVisibleProperty, true),

        new("Theme.Accent.Tool", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Accent.Tool", "Base", "PSurfaceMark", PIconImage.PIconSourceProperty, FrameworkElement.TagProperty),
        new("Theme.Accent.Playback", "Base", null, ButtonBase.CommandProperty, PAccentCommand.PAccentCommandPlayback),
        new("Theme.Accent.Playback", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("play", 24)),
        new("Theme.Accent.Phonetician", "Base", null,
            ButtonBase.CommandProperty, PAccentCommand.PAccentCommandNotation),
        new("Theme.Accent.Phonetician", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("lookup", 24)),
        new("Theme.Accent.Downloader", "Base", null, ButtonBase.CommandProperty, PAccentCommand.PAccentCommandClip),
        new("Theme.Accent.Downloader", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("download", 24)),
        new("Theme.Transcription.Phonetician", "Base", null,
            ButtonBase.CommandProperty, PTranscriptionCommand.PTranscriptionCommandNotation),
        new("Theme.Transcription.Phonetician", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("lookup", 24)),

        new("Theme.Accent.Handle", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Accent.Addition", "Base", null, ButtonBase.CommandProperty, PAccentCommand.PAccentCommandAddition),
        new("Theme.Accent.Addition", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("add", 12)),
        new("Theme.Accent.Remove", "Base", null, ButtonBase.CommandProperty, PAccentCommand.PAccentCommandRemoval),
        new("Theme.Accent.Remove", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("remove", 12)),
        new("Theme.Transcription.Addition", "Base", null,
            ButtonBase.CommandProperty, PTranscriptionCommand.PTranscriptionCommandAddition),
        new("Theme.Transcription.Remove", "Base", null,
            ButtonBase.CommandProperty, PTranscriptionCommand.PTranscriptionCommandRemoval),
        new("Theme.Reflex.Star", "Base", null, ButtonBase.CommandProperty, PReflexCommand.PReflexCommandMain),
        new("Theme.Reflex.Star", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("star", 12)),
        new("Theme.Reflex.Addition", "Base", null, ButtonBase.CommandProperty, PReflexCommand.PReflexCommandAddition),
        new("Theme.Reflex.Remove", "Base", null, ButtonBase.CommandProperty, PReflexCommand.PReflexCommandRemoval),

        new("Theme.Transcription.Option", "Base", "PSchemeSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Transcription.Option", "Highlight", "PSchemeSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Transcription.Option", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Transcription.Scheme", "Base", "PSchemeHead",
            ToggleButton.IsCheckedProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Transcription.Scheme", "Base", "PSchemeName", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Transcription.Scheme", "Base", "PSchemeName",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Transcription.Scheme", "Base", "PSchemeChevron",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("expand", 12)),
        new("Theme.Transcription.Scheme", "Base", "PART_Popup", Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Transcription.Scheme", "Hover", "PSchemeName", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Transcription.Scheme", "Open", "PSchemeName", TextBlock.ForegroundProperty, "Theme.Accent"),

        new("Theme.Reflex.Label", "Empty", null, UIElement.VisibilityProperty, Visibility.Hidden),
        new("Theme.Reflex.Edge", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Reflex.Minor", "Empty", null, UIElement.VisibilityProperty, Visibility.Hidden),
        new("Theme.Reflex.Anchor", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Reflex.Fold", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Reflex.Fold", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Reflex.Fold", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("expand", 12)),
        new("Theme.Reflex.Fold", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Reflex.Fold", "Check", "PSurfaceMark",
            UIElement.RenderTransformProperty, new RotateTransform(180).GetAsFrozen()),
        new("Theme.Reflex.Fold", "Check", null, ContentControl.ContentProperty, "Reflex.Less"),
        new("Theme.Reflex.Anchoring", "Base", null, ButtonBase.CommandProperty, PReflexCommand.PReflexCommandAnchor),
        new("Theme.Reflex.Anchoring", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Reflex.Anchoring", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Reflex.Anchoring", "Base", "PSurfaceText", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Reflex.Anchoring", "Empty", "PSurfacePrompt", UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Reflex.Anchoring", "Hover", "PSurfaceText", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Reflex.Anchoring", "Hover", "PSurfacePrompt", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Sound.Rebuild", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("rebuild", 18)),
        new("Theme.Sound.Rebuild", "Pending", "PSurfaceMark",
            RotateTransform.AngleProperty,
            new DoubleAnimation(0, 360, TimeSpan.FromSeconds(1)) { RepeatBehavior = RepeatBehavior.Forever }),
        new("Theme.Reflex.Rebuild", "Base", null, ButtonBase.CommandProperty, PReflexCommand.PReflexCommandRenewal),

        new("Theme.Script.Character", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Caption", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Epoch", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Gloss", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Stem.Chip", "Base", null, ButtonBase.CommandProperty, PStemCommand.PStemCommandEntry),
        new("Theme.Stem.Chip", "Base", null, ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Stem.Chip", "Base", "PStemCharacter", TextBlock.TextProperty, FrameworkElement.DataContextProperty),
        new("Theme.Stem.Chip", "Base", "PStemCharacter", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Stem.Chip", "Hover", "PStemCharacter", TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Diwei.Choice", "Base", null, ButtonBase.CommandProperty, PDiweiCommand.PDiweiCommandSwitch),
        new("Theme.Diwei.Choice", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Diwei.Choice", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Diwei.Choice", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Diwei.Ipa", "Base", null, ButtonBase.CommandParameterProperty, false),
        new("Theme.Diwei.Respelling", "Base", null, ButtonBase.CommandParameterProperty, true),
        new("Theme.Diwei.Mark", "Hover", "PTallyPart", TextBlock.TextDecorationsProperty, TextDecorations.Underline),
        new("Theme.Diwei.Mark", "Check", "PTallyPart", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Diwei.Tally", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Diwei.Chip", "Base", null, ButtonBase.CommandProperty, PDiweiCommand.PDiweiCommandEntry),
        new("Theme.Diwei.Chip", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Diwei.Chip", "Base", "PDiweiCharacter",
            TextBlock.TextProperty, FrameworkElement.DataContextProperty),
        new("Theme.Diwei.Chip", "Base", "PDiweiCharacter", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Diwei.Chip", "Hover", "PDiweiCharacter",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Fanqie.Character", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Knot", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Reading", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Label", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Text", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Link", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Link", "Base", "PFanqieSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Fanqie.Link", "Base", "PFanqieWord", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Fanqie.Link", "Base", "PFanqieWord", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Fanqie.Link", "Hover", "PFanqieSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Fanqie.Link", "Press", "PFanqieSurface", UIElement.OpacityProperty, 0.72),
        new("Theme.Fanqie.Link", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Initial", "Base", null, ButtonBase.CommandProperty, PFanqieCommand.PFanqieCommandInitial),
        new("Theme.Fanqie.Rime", "Base", null, ButtonBase.CommandProperty, PFanqieCommand.PFanqieCommandRime),
        new("Theme.Fanqie.StemKey", "Base", null, ButtonBase.CommandProperty, PFanqieCommand.PFanqieCommandStem),
        new("Theme.Fanqie.StemKey", "Base", null, ContentControl.ContentProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Representative", "Base", null,
            ButtonBase.CommandProperty, PFanqieCommand.PFanqieCommandRepresentative),
        new("Theme.Fanqie.Representative", "Base", null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Representative", "Base", "PFanqieStar",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("star", 14)),
        new("Theme.Fanqie.Representative", "Base", "PFanqieOrder",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Fanqie.Representative", "Hover", "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Fanqie.Representative", "Press", "PSurface", UIElement.OpacityProperty, 0.5),
        new("Theme.Fanqie.Representative", "Hover", "PFanqieStar", UIElement.OpacityProperty, 0.55),
        new("Theme.Fanqie.Representative", "Marked", "PFanqieStar", UIElement.OpacityProperty, 1.0),
        new("Theme.Fanqie.Representative", "Marked", "PFanqieOrder", UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Fanqie.Representative", "Marked", null,
            FrameworkElement.ToolTipProperty, "Display.FanqieRepresentativeMarked"),
        new("Theme.Fanqie.Representative", "Faded", "PFanqieStar", UIElement.OpacityProperty, 1.0),
        new("Theme.Fanqie.Representative", "Faded", "PFanqieOrder", UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Fanqie.Representative", "Faded", null,
            FrameworkElement.ToolTipProperty, "Display.FanqieRepresentativeMarked"),
        new("Theme.Fanqie.Representative", "Faded", null, UIElement.OpacityProperty, 0.62),

        new("Articulation.Glyph", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Articulation.Glyph", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Articulation.Glyph", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Articulation.Glyph", "Press", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Clip.Preview", "Refused", "PSurface", Border.BackgroundProperty, "Theme.Warning"),
        new("Theme.Clip.Preview", "Refused", null, Control.ForegroundProperty, "Theme.Surface"),
        new("Theme.Clip.Preview", "Fetching", "PSurface", Border.BackgroundProperty, "Theme.Pending"),
        new("Theme.Clip.Preview", "Fetching", null, Control.ForegroundProperty, "Theme.Surface"),
        new("Theme.Clip.Preview", "Playing", "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Clip.Preview", "Playing", null, Control.ForegroundProperty, "Theme.Surface"),
    ];
}
