using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;

namespace Llyn.UIDeportment;

internal static class PLookSheet
{
    internal static readonly IReadOnlyList<PLook.PLookSetter> PLookSheetState =
    [
        new("ScrollBar", "Horizontal", null, FrameworkElement.WidthProperty, double.NaN),
        new("ScrollBar", "Horizontal", null, FrameworkElement.MinWidthProperty, 0.0),
        new("ScrollBar", "Horizontal", null, FrameworkElement.HeightProperty, 14.0),
        new("ScrollBar", "Horizontal", null, FrameworkElement.MinHeightProperty, 14.0),
        new("ScrollBar", "Horizontal", null, Control.TemplateProperty, "Theme.ScrollBar.Horizontal.Template"),

        new("Theme.Navigation.Tab", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceStack", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceIcon", PIconImage.PIconSourceProperty, PTab.PTabIconProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Navigation.Tab", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Navigation.Tab", "Hover", "PSurface", Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Navigation.Tab", "Hover", null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Navigation.Tab", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Tab", "Chosen", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Tab", "Chosen", "PSurfaceBar", UIElement.OpacityProperty, 1.0),
        new("Theme.Navigation.Tab", "Chosen", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Navigation.Tab", "Chosen", null, Control.FontWeightProperty, FontWeights.SemiBold),

        new("Theme.Navigation.Voyage", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Navigation.Voyage", "Hover", "PSurface", Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Navigation.Voyage", "Hover", null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Navigation.Voyage", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Voyage", "Disabled", null, UIElement.OpacityProperty, 0.35),
        new("Theme.Navigation.Voyage", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.Choice", "Base", "PChoiceSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Choice", "Base", "PChoiceSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Choice", "Base", "PChoiceSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Choice", "Base", "PChoiceButton",
            ToggleButton.IsCheckedProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Input.Choice", "Base", "PChoiceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Choice", "Base", "PChoiceContent",
            ContentPresenter.ContentProperty, ComboBox.SelectionBoxItemProperty),
        new("Theme.Input.Choice", "Base", "PChoiceContent",
            ContentPresenter.ContentTemplateProperty, ComboBox.SelectionBoxItemTemplateProperty),
        new("Theme.Input.Choice", "Base", "PART_Popup", Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Input.Choice", "Base", "PART_Popup",
            FrameworkElement.WidthProperty, FrameworkElement.ActualWidthProperty),
        new("Theme.Input.Choice", "Hover", "PChoiceSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.Choice", "Focus", "PChoiceSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Text.Reading", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Input.Action", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Action", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Action", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Action", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.Action", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.Action", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Input.Pill", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Pill", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Pill", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Pill", "Base", "PSurfaceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Pill", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.Pill", "Disabled", "PSurface", UIElement.OpacityProperty, 0.4),
        new("Theme.Input.Pill", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.Primary", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Primary", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Primary", "Base", "PSurfaceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Primary", "Hover", "PSurface",
            Border.BackgroundProperty, new SolidColorBrush(Color.FromRgb(0x24, 0x5F, 0xD0))),
        new("Theme.Input.Primary", "Press", "PSurface",
            Border.BackgroundProperty, new SolidColorBrush(Color.FromRgb(0x1D, 0x50, 0xB5))),
        new("Theme.Input.Primary", "Disabled", "PSurface", UIElement.OpacityProperty, 0.4),
        new("Theme.Input.Primary", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.Bin", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Bin", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Bin", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Bin", "Hover", "PSurface", Border.BackgroundProperty, "Theme.WarningSoft"),
        new("Theme.Input.Bin", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Warning"),
        new("Theme.Input.Bin", "Hover", null, Control.ForegroundProperty, "Theme.Warning"),
        new("Theme.Input.Bin", "Press", "PSurface", Border.BackgroundProperty, "Theme.WarningSoft"),
        new("Theme.Input.Bin", "Press", "PSurface", Border.BorderBrushProperty, "Theme.WarningStrong"),
        new("Theme.Input.Bin", "Press", null, Control.ForegroundProperty, "Theme.WarningStrong"),
        new("Theme.Input.Bin", "Disabled", "PSurface", Border.BackgroundProperty, Brushes.Transparent),
        new("Theme.Input.Bin", "Disabled", "PSurface", Border.BorderBrushProperty, "Theme.DisabledLine"),
        new("Theme.Input.Bin", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Input.Bin", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.TogglePill", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.TogglePill", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.TogglePill", "Base", "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.TogglePill", "Base", "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.TogglePill", "Base", "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Input.TogglePill", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.TogglePill", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.TogglePill", "Check", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Input.ToggleAction", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.ToggleAction", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.ToggleAction", "Base", "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.ToggleAction", "Base", "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.ToggleAction", "Base", "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Input.ToggleAction", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.ToggleAction", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.ToggleAction", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Input.ToggleAction", "Check", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Input.Tab", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Input.Tab", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Input.Tab", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Input.Tab", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Input.Tab", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Input.Tab", "Hover+Idle", "PSurface", Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Input.Tab", "Hover+Idle", null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Input.Tab", "Selected", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Popup.ProgressBar", "Base", null,
            TranslateTransform.XProperty,
            new DoubleAnimation(-84, 268, TimeSpan.FromSeconds(1.15)) { RepeatBehavior = RepeatBehavior.Forever }),

        new("Theme.Popup.RowSurface", "Hover", null, Border.BackgroundProperty, "Theme.SurfaceRaised"),

        new("Editor.Popup.Row", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Editor.Popup.Row", "Selected", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Editor.Card.Add", "Base", "PSurfaceIcon", PIconImage.PIconSourceProperty, PIcon.PIconResolve("add", 12)),

        new("Theme.Popup.RowChoice", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.RowChoice", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Popup.RowChoice", "Base", "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Popup.RowChoice", "Base", "PLabel", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Popup.RowChoice", "Base", "PLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Popup.RowChoice", "Base", "PLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Popup.RowChoice", "Base", "PLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Popup.RowChoice", "Base", "PLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Popup.RowChoice", "Hover", "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Popup.RowChoice", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Popup.RowChoice", "Hover", "PLabel", TextBlock.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowChoice", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowChoice", "Press", "PSurface", Border.BorderBrushProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowChoice", "Press", "PLabel", TextBlock.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowChoice", "Disabled", "PSurface", Border.BackgroundProperty, Brushes.Transparent),
        new("Theme.Popup.RowChoice", "Disabled", "PSurface", Border.BorderBrushProperty, "Theme.DisabledLine"),
        new("Theme.Popup.RowChoice", "Disabled", "PLabel", TextBlock.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Popup.RowChoice", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Popup.RowReading", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Popup.RowReading", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.RowReading", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Popup.RowReading", "Base", "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Popup.RowReading", "Hover", "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Popup.RowReading", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Popup.RowReading", "Hover", null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowReading", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowReading", "Press", "PSurface", Border.BorderBrushProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowReading", "Press", null, Control.ForegroundProperty, "Theme.Roof"),

        new("Theme.Popup.IconAction", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.IconAction", "Hover", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Popup.IconAction", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Popup.IconAction", "Press", "PSurface", UIElement.OpacityProperty, 0.7),

        new("Theme.Search.Bar", "Hover", null, Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Search.Bar", "Focus", null, Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Search.Dropper", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Search.Dropper", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Search.Dropper", "Hover", null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Search.Dropper", "Check", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Search.Dropper", "Check", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Search.Helper", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Search.Helper", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Search.Helper", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceStack", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, FrameworkElement.TagProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Search.Helper", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Search.Helper", "Bare", "PSurfaceMark", UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Search.Helper", "Mute", "PSurfaceLabel", UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Search.Helper", "Mute", "PSurfaceMark", FrameworkElement.MarginProperty, new Thickness(0)),
        new("Theme.Search.Helper", "Mute", null, Control.PaddingProperty, new Thickness(11, 0, 11, 0)),
        new("Theme.Search.Helper", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Search.Helper", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Search.Helper", "Check", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Search.Helper", "Check", "PSurface", Border.BorderBrushProperty, "Theme.AccentEdge"),
        new("Theme.Search.Helper", "Check", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Search.Helper", "Check", null, Control.FontWeightProperty, FontWeights.SemiBold),

        new("Theme.Catalog.Row", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Catalog.Row", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Catalog.Row", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Catalog.Row", "Base", "PSurfaceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Catalog.Row", "Base", "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Catalog.Row", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Catalog.Row", "Press", "PSurface", UIElement.OpacityProperty, 0.78),
        new("Theme.Catalog.Row", "Chosen", null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Catalog.Row", "Chosen", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Choice.Row", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Row", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Row", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Choice.Row", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Choice.Row", "Base", "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Choice.Row", "Hover", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Row", "Press", "PSurface", UIElement.OpacityProperty, 0.72),

        new("Theme.Choice.Order", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Order", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Order", "Base", "PIndicator",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("check", 12)),
        new("Theme.Choice.Order", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Choice.Order", "Check", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Order", "Check", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Choice.Order", "Check", "PIndicator", UIElement.VisibilityProperty, Visibility.Visible),

        new("Theme.Choice.Filter", "Base", "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Filter", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Filter", "Base", "PIndicatorMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("check", 12)),
        new("Theme.Choice.Filter", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Choice.Filter", "Check", null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Choice.Filter", "Check", "PIndicator", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Choice.Filter", "Check", "PIndicator", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Filter", "Check", "PIndicatorMark", UIElement.VisibilityProperty, Visibility.Visible),

        new("Theme.Choice.Item", "Base", "PChoiceSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Item", "Hover", "PChoiceSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Item", "Highlight", "PChoiceSurface", Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Choice.Bare", "Base", "PChoiceHint", TextBlock.FontFamilyProperty, Control.FontFamilyProperty),
        new("Theme.Choice.Bare", "Base", "PChoiceHint", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Choice.Bare", "Base", "PChoiceHint", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Choice.Bare", "Base", "PChoiceHint", TextBlock.TextProperty, FrameworkElement.TagProperty),
        new("Theme.Choice.Bare", "Base", "PART_EditableTextBox",
            Control.FontFamilyProperty, Control.FontFamilyProperty),
        new("Theme.Choice.Bare", "Base", "PART_EditableTextBox", Control.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Choice.Bare", "Base", "PART_EditableTextBox",
            Control.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Choice.Bare", "Base", "PART_EditableTextBox",
            Control.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Choice.Bare", "Base", "PART_Popup", Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Choice.Bare", "Empty", "PChoiceHint", UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Choice.Bare", "Hover", "PChoiceRing", Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Choice.Bare", "Focus", "PChoiceRing", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Choice.Bare", "Focus", "PChoiceHint", UIElement.OpacityProperty, 0.36),

        new("Theme.Choice.Switch", "Hover", "PChoiceTrack", Border.BackgroundProperty, "Theme.LineStrong"),
        new("Theme.Choice.Switch", "Check", "PChoiceTrack", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Choice.Switch", "Check", "PChoiceKnob",
            FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Right),
        new("Theme.Choice.Switch", "Check", "PChoiceKnob", FrameworkElement.MarginProperty, new Thickness(0, 0, 3, 0)),
        new("Theme.Choice.Switch", "Hover+Check", "PChoiceTrack", Border.BackgroundProperty, "Theme.AccentHover"),
        new("Theme.Choice.Switch", "Disabled", "PChoiceTrack", Border.BackgroundProperty, "Theme.DisabledLine"),

        new("Theme.Command.Group", "Disabled", null, UIElement.OpacityProperty, 0.55),

        new("Theme.Command.IconToggle", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.IconToggle", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.IconToggle", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.IconToggle", "Check", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.IconToggle", "Check", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.IconToggle", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.IconToggle", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Icon", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Icon", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Icon", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Icon", "Press", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Icon", "Press", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Icon", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Icon", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Segment", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Segment", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceStack", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, FrameworkElement.TagProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Segment", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Segment", "Bare", "PSurfaceMark", UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Segment", "Hover", null, Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Segment", "Focus", null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Segment", "Press", null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Segment", "Press", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Segment", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Segment", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Primary", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Primary", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceStack", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceMark",
            PIconImage.PIconSourceProperty, FrameworkElement.TagProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Primary", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Primary", "Bare", "PSurfaceMark", UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Primary", "Focus", null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Primary", "Hover", null, Control.BackgroundProperty, "Theme.AccentHover"),
        new("Theme.Command.Primary", "Press", null, Control.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Command.Primary", "Press", null, Control.ForegroundProperty, Brushes.White),
        new("Theme.Command.Primary", "Disabled", null, Control.BackgroundProperty, Brushes.Transparent),
        new("Theme.Command.Primary", "Disabled", null, Control.BorderBrushProperty, Brushes.Transparent),
        new("Theme.Command.Primary", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Primary", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Mode", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Mode", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceStack", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceMark", PIconImage.PIconSourceProperty, FrameworkElement.TagProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceLabel", TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceLabel", TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceLabel", TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Mode", "Base", "PSurfaceLabel", TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Mode", "Bare", "PSurfaceMark", UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Mode", "Hover", null, Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Mode", "Focus", null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Mode", "Press", null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Mode", "Press", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Mode", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),
        new("Theme.Command.Mode", "Check", null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Mode", "Check", null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Mode", "Check", null, Control.FontWeightProperty, FontWeights.SemiBold),
        new("Theme.Command.Mode", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Mode", "Disabled", null, Control.BackgroundProperty, Brushes.Transparent),
        new("Theme.Command.Mode", "Disabled+Check", null, Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Mode", "Disabled+Check", null, Control.FontWeightProperty, FontWeights.SemiBold),

        new("Theme.Language.Expand", "Base", null, PIconImage.PIconSourceProperty, PIcon.PIconResolve("expand", 12)),

        new("Theme.Language.Toggle", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Language.Toggle", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Language.Toggle", "Base", "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Language.Toggle", "Base", "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Language.Toggle", "Base", "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Language.Toggle", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Language.Toggle", "Check", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Paradigm.Part", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Playback.Action", "Hover", "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Playback.Action", "Press", "PSurface", UIElement.OpacityProperty, 1.0),
        new("Theme.Playback.Action", "Press", "PSurface", UIElement.RenderTransformOriginProperty, new Point(0.5, 0.5)),
        new("Theme.Playback.Action", "Press", "PSurface",
            UIElement.RenderTransformProperty, new ScaleTransform(0.88, 0.88).GetAsFrozen()),
        new("Theme.Playback.Action", "Disabled", null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Playback.Action", "Disabled", null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Volume.Rail", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),

        new("Theme.Volume.Thumb", "Hover", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Volume.Thumb", "Drag", "PSurface", Border.BackgroundProperty, "Theme.Accent"),

        new("Theme.Volume.Slider", "Base", "PSurface", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Volume.Slider", "Base", "PSurfaceLower", ButtonBase.CommandProperty, Slider.DecreaseLarge),
        new("Theme.Volume.Slider", "Base", "PSurfaceUpper", ButtonBase.CommandProperty, Slider.IncreaseLarge),
        new("Theme.Volume.Slider", "Disabled", "PSurface", UIElement.OpacityProperty, 0.45),

        new("Theme.Caption.Button", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Caption.Button", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Caption.Button", "Hover", null, Control.ForegroundProperty, "Theme.Ink"),

        new("Theme.Caption.Close", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Caption.Close", "Hover", "PSurface", Border.BackgroundProperty, "Theme.WarningStrong"),
        new("Theme.Caption.Close", "Hover", null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Caption.Close", "Press", "PSurface", Border.BackgroundProperty, "Theme.WarningStrong"),
        new("Theme.Caption.Close", "Press", "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Caption.Close", "Press", null, Control.ForegroundProperty, "Theme.Roof"),

        new("Theme.Category.Item", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Category.Item", "Base", "PSurfaceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Category.Item", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Category.Item", "Press", "PSurface", UIElement.OpacityProperty, 0.8),

        new("Theme.Card.Switch", "Base", "PCardSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Card.Switch", "Hover", "PCardSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Card.Switch", "Check", "PCardSurface", Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Favorite.Mark", "Base", "PSurfaceContent", FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Favorite.Mark", "Base", "PFavoriteMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("favorite", 24)),
        new("Theme.Favorite.Mark", "Hover", "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Favorite.Mark", "Press", "PSurface", UIElement.OpacityProperty, 0.5),
        new("Theme.Favorite.Mark", "Check", "PFavoriteMark",
            PIconImage.PIconSourceProperty, PIcon.PIconResolve("favorite-marked", 24)),

        new("Theme.Marker.Surface", "Hover", null, Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Marker.Remove", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Marker.Remove", "Hover", "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Marker.Remove", "Hover", null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Marker.Remove", "Hover", null, UIElement.OpacityProperty, 1.0),
        new("Theme.Marker.Remove", "Press", "PSurface", UIElement.OpacityProperty, 0.75),

        new("Theme.Marker.Field", "Hover", null, Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Marker.Field", "Focus", null, Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Marker.Field", "Focus", null, Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Marker.Switch", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Marker.Switch", "Hover", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Marker.Switch", "Hover", null, UIElement.OpacityProperty, 1.0),
        new("Theme.Marker.Switch", "Check", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Marker.Switch", "Check", "PSurfaceMark",
            UIElement.RenderTransformProperty, new RotateTransform(180).GetAsFrozen()),
        new("Theme.Marker.Switch", "Check", null, UIElement.OpacityProperty, 1.0),

        new("Theme.Glyph.Phonetician", "Base", null, ButtonBase.CommandProperty, PGlyphCommand.PGlyphCommandNotation),

        new("Theme.Glyph.Chip", "Base", null, ButtonBase.CommandProperty, PGlyphCommand.PGlyphCommandEntry),
        new("Theme.Glyph.Chip", "Hover", "PGlyphCharacter", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Glyph.Chip", "Hover", "PGlyphCharacter",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Gloss.Line", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Gloss.Choice", "Hover", "PGlossSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Gloss.Choice", "Selected", "PGlossSurface", Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Gloss.Remove", "Base", null, ButtonBase.CommandProperty, PGlossCommand.PGlossCommandRemoval),
        new("Theme.Gloss.Remove", "Base", "PSurface", Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Gloss.Remove", "Base", "PSurface", Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Gloss.Remove", "Base", "PSurface", Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Gloss.Remove", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Gloss.Remove", "Hover", "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Gloss.Remove", "Hover", null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Mention.Line", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Mention.Item", "Hover", "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Mention.Item", "Selected", "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Mention.Sense", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Atlas.Kind", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Vignette.Picture", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Vignette.Video", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Excerpt.Flag", "Empty", null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Transcript.Row", "Hover", "PTranscriptShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Transcript.Row", "Hover", "PTranscriptShelf", UIElement.IsHitTestVisibleProperty, true),
        new("Theme.Transcript.Row", "Focus", "PTranscriptShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Transcript.Row", "Focus", "PTranscriptShelf", UIElement.IsHitTestVisibleProperty, true),
        new("Imprint.Credit.Handle", "Disabled", null, UIElement.OpacityProperty, 0.35),

        new("ContextMenu", "Base", "PMentionLink", MenuItem.CommandProperty, PMentionCommand.PMentionCommandLink),
        new("ContextMenu", "Base", "PMentionChoose", MenuItem.CommandProperty, PMentionCommand.PMentionCommandChoose),
        new("ContextMenu", "Base", "PMentionSilence", MenuItem.CommandProperty, PMentionCommand.PMentionCommandSilence),
        new("ContextMenu", "Base", "PMentionUnlink", MenuItem.CommandProperty, PMentionCommand.PMentionCommandUnlink),
        new("ContextMenu", "Base", "PEtymologyLink", MenuItem.CommandProperty, PEtymologyCommand.PEtymologyCommandLink),
        new("ContextMenu", "Base", "PEtymologyUnlink",
            MenuItem.CommandProperty, PEtymologyCommand.PEtymologyCommandUnlink),
        new("ContextMenu", "Base", "PMentionCut", MenuItem.CommandProperty, ApplicationCommands.Cut),
        new("ContextMenu", "Base", "PMentionClip", MenuItem.CommandProperty, ApplicationCommands.Copy),
        new("ContextMenu", "Base", "PMentionPaste", MenuItem.CommandProperty, ApplicationCommands.Paste),

        .. PLookSound.PLookSoundState,
        .. PLookDisplay.PLookDisplayState,

    ];
}
