using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;

namespace Llyn.UIDeportment;

internal static class QLookSheet
{
    internal static readonly IReadOnlyList<QLook.QLookSetter> QLookSheetState =
    [
        new("ScrollBar", QLookCue.QLookCueHorizontal, null, FrameworkElement.WidthProperty, double.NaN),
        new("ScrollBar", QLookCue.QLookCueHorizontal, null, FrameworkElement.MinWidthProperty, 0.0),
        new("ScrollBar", QLookCue.QLookCueHorizontal, null, FrameworkElement.HeightProperty, 14.0),
        new("ScrollBar", QLookCue.QLookCueHorizontal, null, FrameworkElement.MinHeightProperty, 14.0),
        new("ScrollBar", QLookCue.QLookCueHorizontal, null,
            Control.TemplateProperty, "Theme.ScrollBar.Horizontal.Template"),

        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceStack",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceIcon",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Navigation.Tab", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Navigation.Tab", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Navigation.Tab", QLookCue.QLookCuePress, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Tab", QLookCue.QLookCueChosen, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Tab", QLookCue.QLookCueChosen, "PSurfaceBar", UIElement.OpacityProperty, 1.0),
        new("Theme.Navigation.Tab", QLookCue.QLookCueChosen, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Navigation.Tab", QLookCue.QLookCueChosen, null, Control.FontWeightProperty, FontWeights.SemiBold),

        new("Theme.Navigation.Voyage", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Navigation.Voyage", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Navigation.Voyage", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Navigation.Voyage", QLookCue.QLookCuePress, "PSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Navigation.Voyage", QLookCue.QLookCueDisabled, null, UIElement.OpacityProperty, 0.35),
        new("Theme.Navigation.Voyage", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Text.Reading", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Popup.ProgressBar", QLookCue.QLookCueBase, null,
            TranslateTransform.XProperty,
            QContract.QContractSheetFind<AnimationTimeline>("Theme.Popup.ProgressBar.Sweep")),

        new("Theme.Popup.RowSurface", QLookCue.QLookCueHover, null, Border.BackgroundProperty, "Theme.SurfaceRaised"),

        new("Editor.Popup.Row", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Editor.Popup.Row", QLookCue.QLookCueSelected, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Editor.Card.Add", QLookCue.QLookCueBase, "PSurfaceIcon",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("add", 12)),

        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PLabel",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueBase, "PLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueHover, "PLabel", TextBlock.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCuePress, "PSurface",
            Border.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCuePress, "PSurface",
            Border.BorderBrushProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCuePress, "PLabel", TextBlock.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueDisabled, "PSurface",
            Border.BackgroundProperty, Brushes.Transparent),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueDisabled, "PSurface",
            Border.BorderBrushProperty, "Theme.DisabledLine"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueDisabled, "PLabel",
            TextBlock.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Popup.RowChoice", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Popup.RowReading", QLookCue.QLookCueBase, "PSurface",
            Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Popup.RowReading", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.RowReading", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Popup.RowReading", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Popup.RowReading", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Popup.RowReading", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Popup.RowReading", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Popup.RowReading", QLookCue.QLookCuePress, "PSurface",
            Border.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowReading", QLookCue.QLookCuePress, "PSurface",
            Border.BorderBrushProperty, "Theme.AccentPress"),
        new("Theme.Popup.RowReading", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Roof"),

        new("Theme.Popup.IconAction", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Popup.IconAction", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Popup.IconAction", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Popup.IconAction", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.7),

        new("Theme.Caption.Button", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Caption.Button", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Caption.Button", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Ink"),

        new("Theme.Caption.Close", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Caption.Close", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.WarningStrong"),
        new("Theme.Caption.Close", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Caption.Close", QLookCue.QLookCuePress, "PSurface",
            Border.BackgroundProperty, "Theme.WarningStrong"),
        new("Theme.Caption.Close", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Caption.Close", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Roof"),

        new("Theme.Category.Item", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Category.Item", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Category.Item", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Category.Item", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.8),

        new("Theme.Card.Switch", QLookCue.QLookCueBase, "PCardSurface",
            Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Card.Switch", QLookCue.QLookCueHover, "PCardSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Card.Switch", QLookCue.QLookCueChecked, "PCardSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Favorite.Mark", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Favorite.Mark", QLookCue.QLookCueBase, "PFavoriteMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("favorite", 24)),
        new("Theme.Favorite.Mark", QLookCue.QLookCueHover, "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Favorite.Mark", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.5),
        new("Theme.Favorite.Mark", QLookCue.QLookCueChecked, "PFavoriteMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("favorite-marked", 24)),

        new("Theme.Marker.Surface", QLookCue.QLookCueHover, null, Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Marker.Remove", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Marker.Remove", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Marker.Remove", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Marker.Remove", QLookCue.QLookCueHover, null, UIElement.OpacityProperty, 1.0),
        new("Theme.Marker.Remove", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.75),

        new("Theme.Marker.Field", QLookCue.QLookCueHover, null, Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Marker.Field", QLookCue.QLookCueFocus, null, Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Marker.Field", QLookCue.QLookCueFocus, null, Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Marker.Switch", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Marker.Switch", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Marker.Switch", QLookCue.QLookCueHover, null, UIElement.OpacityProperty, 1.0),
        new("Theme.Marker.Switch", QLookCue.QLookCueChecked, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Marker.Switch", QLookCue.QLookCueChecked, "PSurfaceMark",
            UIElement.RenderTransformProperty, new RotateTransform(180).GetAsFrozen()),
        new("Theme.Marker.Switch", QLookCue.QLookCueChecked, null, UIElement.OpacityProperty, 1.0),

        new("Theme.Paradigm.Fold", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Paradigm.Fold", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Glyph.Phonetician", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QGlyphCommand.QGlyphCommandNotation),

        new("Theme.Glyph.Chip", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QGlyphCommand.QGlyphCommandEntry),
        new("Theme.Glyph.Chip", QLookCue.QLookCueHover, "PGlyphCharacter",
            TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Glyph.Chip", QLookCue.QLookCueHover, "PGlyphCharacter",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Gloss.Line", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Gloss.Choice", QLookCue.QLookCueHover, "PGlossSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Gloss.Choice", QLookCue.QLookCueSelected, "PGlossSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Gloss.Remove", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, PGlossCommand.PGlossCommandRemoval),
        new("Theme.Gloss.Remove", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Gloss.Remove", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Gloss.Remove", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Gloss.Remove", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Gloss.Remove", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Gloss.Remove", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Mention.Line", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Mention.Item", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Mention.Item", QLookCue.QLookCueSelected, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Mention.Sense", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Atlas.Kind", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Vignette.Picture", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Vignette.Video", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Excerpt.Flag", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Transcript.Row", QLookCue.QLookCueHover, "PTranscriptShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Transcript.Row", QLookCue.QLookCueHover, "PTranscriptShelf",
            UIElement.IsHitTestVisibleProperty, true),
        new("Theme.Transcript.Row", QLookCue.QLookCueFocus, "PTranscriptShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Transcript.Row", QLookCue.QLookCueFocus, "PTranscriptShelf",
            UIElement.IsHitTestVisibleProperty, true),
        new("Imprint.Credit.Handle", QLookCue.QLookCueDisabled, null, UIElement.OpacityProperty, 0.35),

        new("ContextMenu", QLookCue.QLookCueBase, "PMentionLink",
            MenuItem.CommandProperty, PMentionCommand.PMentionCommandLink),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionChoose",
            MenuItem.CommandProperty, PMentionCommand.PMentionCommandChoose),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionSilence",
            MenuItem.CommandProperty, PMentionCommand.PMentionCommandSilence),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionUnlink",
            MenuItem.CommandProperty, PMentionCommand.PMentionCommandUnlink),
        new("ContextMenu", QLookCue.QLookCueBase, "PEtymologyLink",
            MenuItem.CommandProperty, PEtymologyCommand.PEtymologyCommandLink),
        new("ContextMenu", QLookCue.QLookCueBase, "PEtymologyUnlink",
            MenuItem.CommandProperty, PEtymologyCommand.PEtymologyCommandUnlink),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionCut", MenuItem.CommandProperty, ApplicationCommands.Cut),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionClip", MenuItem.CommandProperty, ApplicationCommands.Copy),
        new("ContextMenu", QLookCue.QLookCueBase, "PMentionPaste", MenuItem.CommandProperty, ApplicationCommands.Paste),

        .. QLookInput.QLookInputState,
        .. QLookControl.QLookControlState,
        .. QLookSound.QLookSoundState,
        .. QLookDisplay.QLookDisplayState,

    ];
}
