using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;

namespace Llyn.UIDeportment;

internal static class QLookControl
{
    internal static readonly IReadOnlyList<QLook.QLookSetter> QLookControlState =
    [
        new("Theme.Catalog.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Catalog.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Catalog.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Catalog.Row", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Catalog.Row", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Catalog.Row", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Catalog.Row", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.78),
        new("Theme.Catalog.Row", QLookCue.QLookCueChosen, null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Catalog.Row", QLookCue.QLookCueChosen, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Choice.Row", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Choice.Row", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Choice.Row", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Choice.Row", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Row", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.72),

        new("Theme.Choice.Order", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Order", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Order", QLookCue.QLookCueBase, "PIndicator",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("check", 12)),
        new("Theme.Choice.Order", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Choice.Order", QLookCue.QLookCueChecked, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Order", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Choice.Order", QLookCue.QLookCueChecked, "PIndicator",
            UIElement.VisibilityProperty, Visibility.Visible),

        new("Theme.Choice.Filter", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Filter", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Choice.Filter", QLookCue.QLookCueBase, "PIndicatorMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("check", 12)),
        new("Theme.Choice.Filter", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Choice.Filter", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Choice.Filter", QLookCue.QLookCueChecked, "PIndicator", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Choice.Filter", QLookCue.QLookCueChecked, "PIndicator",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Filter", QLookCue.QLookCueChecked, "PIndicatorMark",
            UIElement.VisibilityProperty, Visibility.Visible),

        new("Theme.Choice.Item", QLookCue.QLookCueBase, "PChoiceSurface",
            Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Choice.Item", QLookCue.QLookCueHover, "PChoiceSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Choice.Item", QLookCue.QLookCueHighlight, "PChoiceSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),

        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PChoiceHint",
            TextBlock.FontFamilyProperty, Control.FontFamilyProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PChoiceHint",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PChoiceHint",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PChoiceHint",
            TextBlock.TextProperty, QField.QFieldHintProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PART_EditableTextBox",
            Control.FontFamilyProperty, Control.FontFamilyProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PART_EditableTextBox",
            Control.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PART_EditableTextBox",
            Control.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PART_EditableTextBox",
            Control.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueBase, "PART_Popup",
            Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Choice.Bare", QLookCue.QLookCueEmpty, "PChoiceHint",
            UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Choice.Bare", QLookCue.QLookCueHover, "PChoiceRing", Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Choice.Bare", QLookCue.QLookCueFocus, "PChoiceRing", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Choice.Bare", QLookCue.QLookCueFocus, "PChoiceHint", UIElement.OpacityProperty, 0.36),

        new("Theme.Choice.Switch", QLookCue.QLookCueHover, "PChoiceTrack",
            Border.BackgroundProperty, "Theme.LineStrong"),
        new("Theme.Choice.Switch", QLookCue.QLookCueChecked, "PChoiceTrack", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Choice.Switch", QLookCue.QLookCueChecked, "PChoiceKnob",
            FrameworkElement.HorizontalAlignmentProperty, HorizontalAlignment.Right),
        new("Theme.Choice.Switch", QLookCue.QLookCueChecked, "PChoiceKnob",
            FrameworkElement.MarginProperty, "Theme.Choice.Switch.KnobInset"),
        new("Theme.Choice.Switch", QLookCue.QLookCueHover | QLookCue.QLookCueChecked, "PChoiceTrack",
            Border.BackgroundProperty, "Theme.AccentHover"),
        new("Theme.Choice.Switch", QLookCue.QLookCueDisabled, "PChoiceTrack",
            Border.BackgroundProperty, "Theme.DisabledLine"),

        new("Theme.Command.Group", QLookCue.QLookCueDisabled, null, UIElement.OpacityProperty, 0.55),

        new("Theme.Command.IconToggle", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.IconToggle", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.IconToggle", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.IconToggle", QLookCue.QLookCueChecked, "PSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.IconToggle", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.IconToggle", QLookCue.QLookCueDisabled, null,
            Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.IconToggle", QLookCue.QLookCueDisabled, null,
            FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Icon", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Icon", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Icon", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Icon", QLookCue.QLookCuePress, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Icon", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Icon", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Icon", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceStack",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Segment", QLookCue.QLookCueBare, "PSurfaceMark",
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Segment", QLookCue.QLookCueHover, null, Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Segment", QLookCue.QLookCueFocus, null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Segment", QLookCue.QLookCuePress, null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Segment", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Segment", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Segment", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceStack",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Primary", QLookCue.QLookCueBare, "PSurfaceMark",
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Primary", QLookCue.QLookCueFocus, null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Primary", QLookCue.QLookCueHover, null, Control.BackgroundProperty, "Theme.AccentHover"),
        new("Theme.Command.Primary", QLookCue.QLookCuePress, null, Control.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Command.Primary", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Roof"),
        new("Theme.Command.Primary", QLookCue.QLookCueDisabled, null, Control.BackgroundProperty, Brushes.Transparent),
        new("Theme.Command.Primary", QLookCue.QLookCueDisabled, null, Control.BorderBrushProperty, Brushes.Transparent),
        new("Theme.Command.Primary", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Primary", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceStack",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Command.Mode", QLookCue.QLookCueBare, "PSurfaceMark",
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Command.Mode", QLookCue.QLookCueHover, null, Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Mode", QLookCue.QLookCueFocus, null, Control.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Command.Mode", QLookCue.QLookCuePress, null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Mode", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Mode", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),
        new("Theme.Command.Mode", QLookCue.QLookCueChecked, null, Control.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Command.Mode", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Command.Mode", QLookCue.QLookCueChecked, null, Control.FontWeightProperty, FontWeights.SemiBold),
        new("Theme.Command.Mode", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Command.Mode", QLookCue.QLookCueDisabled, null, Control.BackgroundProperty, Brushes.Transparent),
        new("Theme.Command.Mode", QLookCue.QLookCueDisabled | QLookCue.QLookCueChecked, null,
            Control.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Command.Mode", QLookCue.QLookCueDisabled | QLookCue.QLookCueChecked, null,
            Control.FontWeightProperty, FontWeights.SemiBold),

        new("Theme.Language.Expand", QLookCue.QLookCueBase, null,
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("expand", 12)),

        new("Theme.Language.Toggle", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Language.Toggle", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Language.Toggle", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Language.Toggle", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Language.Toggle", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Language.Toggle", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Language.Toggle", QLookCue.QLookCueChecked, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Paradigm.Part", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Playback.Action", QLookCue.QLookCueHover, "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Playback.Action", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 1.0),
        new("Theme.Playback.Action", QLookCue.QLookCuePress, "PSurface",
            UIElement.RenderTransformOriginProperty, new Point(0.5, 0.5)),
        new("Theme.Playback.Action", QLookCue.QLookCuePress, "PSurface",
            UIElement.RenderTransformProperty, "Theme.Playback.Action.PressScale"),
        new("Theme.Playback.Action", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Playback.Action", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Volume.Rail", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),

        new("Theme.Volume.Thumb", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Volume.Thumb", QLookCue.QLookCueDrag, "PSurface", Border.BackgroundProperty, "Theme.Accent"),

        new("Theme.Volume.Slider", QLookCue.QLookCueBase, "PSurface",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Volume.Slider", QLookCue.QLookCueBase, "PSurfaceLower",
            ButtonBase.CommandProperty, Slider.DecreaseLarge),
        new("Theme.Volume.Slider", QLookCue.QLookCueBase, "PSurfaceUpper",
            ButtonBase.CommandProperty, Slider.IncreaseLarge),
        new("Theme.Volume.Slider", QLookCue.QLookCueDisabled, "PSurface", UIElement.OpacityProperty, 0.45),
    ];
}
