using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Animation;

namespace Llyn.UIDeportment;

internal static class QLookSound
{
    internal static readonly IReadOnlyList<QLook.QLookSetter> QLookSoundState =
    [
        new("Theme.Pronunciation.Flag", QLookCue.QLookCueEmpty, null,
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Pronunciation.Label", QLookCue.QLookCueEmpty, null,
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Pronunciation.Surface", QLookCue.QLookCueHover, "PAccentShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Pronunciation.Surface", QLookCue.QLookCueHover, "PAccentShelf",
            UIElement.IsHitTestVisibleProperty, true),
        new("Theme.Pronunciation.Surface", QLookCue.QLookCueFocus, "PAccentShelf", UIElement.OpacityProperty, 1.0),
        new("Theme.Pronunciation.Surface", QLookCue.QLookCueFocus, "PAccentShelf",
            UIElement.IsHitTestVisibleProperty, true),

        new("Theme.Accent.Tool", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Accent.Tool", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Accent.Playback", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QAccentCommand.QAccentCommandPlayback),
        new("Theme.Accent.Playback", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("play", 24)),
        new("Theme.Accent.Phonetician", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QAccentCommand.QAccentCommandNotation),
        new("Theme.Accent.Phonetician", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("lookup", 24)),
        new("Theme.Accent.Downloader", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QAccentCommand.QAccentCommandClip),
        new("Theme.Accent.Downloader", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("download", 24)),
        new("Theme.Transcription.Phonetician", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QTranscriptionCommand.QTranscriptionCommandNotation),
        new("Theme.Transcription.Phonetician", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("lookup", 24)),

        new("Theme.Accent.Handle", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Accent.Addition", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QAccentCommand.QAccentCommandAddition),
        new("Theme.Accent.Addition", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("add", 12)),
        new("Theme.Accent.Remove", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QAccentCommand.QAccentCommandRemoval),
        new("Theme.Accent.Remove", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("remove", 12)),
        new("Theme.Transcription.Addition", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QTranscriptionCommand.QTranscriptionCommandAddition),
        new("Theme.Transcription.Remove", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QTranscriptionCommand.QTranscriptionCommandRemoval),
        new("Theme.Reflex.Star", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QReflexCommand.QReflexCommandMain),
        new("Theme.Reflex.Star", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("star", 12)),
        new("Theme.Reflex.Addition", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QReflexCommand.QReflexCommandAddition),
        new("Theme.Reflex.Remove", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QReflexCommand.QReflexCommandRemoval),

        new("Theme.Transcription.Option", QLookCue.QLookCueBase, "PSchemeSurface",
            Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Transcription.Option", QLookCue.QLookCueHighlight, "PSchemeSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Transcription.Option", QLookCue.QLookCueDisabled, null,
            Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueBase, "PSchemeHead",
            ToggleButton.IsCheckedProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueBase, "PSchemeName",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueBase, "PSchemeName",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueBase, "PSchemeChevron",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("expand", 12)),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueBase, "PART_Popup",
            Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueHover, "PSchemeName",
            TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Transcription.Scheme", QLookCue.QLookCueOpened, "PSchemeName",
            TextBlock.ForegroundProperty, "Theme.Accent"),

        new("Theme.Reflex.Label", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Hidden),
        new("Theme.Reflex.Edge", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Reflex.Minor", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Hidden),
        new("Theme.Reflex.Anchor", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Reflex.Fold", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Reflex.Fold", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Reflex.Fold", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("expand", 12)),
        new("Theme.Reflex.Fold", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Reflex.Fold", QLookCue.QLookCueChecked, "PSurfaceMark",
            UIElement.RenderTransformProperty, new RotateTransform(180).GetAsFrozen()),
        new("Theme.Reflex.Fold", QLookCue.QLookCueChecked, null, ContentControl.ContentProperty, "Reflex.Less"),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QReflexCommand.QReflexCommandAnchor),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueBase, "PSurfaceText",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueEmpty, "PSurfacePrompt",
            UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueHover, "PSurfaceText",
            TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Reflex.Anchoring", QLookCue.QLookCueHover, "PSurfacePrompt",
            TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Sound.Rebuild", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("rebuild", 18)),
        new("Theme.Sound.Rebuild", QLookCue.QLookCuePending, "PSurfaceMark",
            RotateTransform.AngleProperty,
            QContract.QContractSheetFind<AnimationTimeline>("Theme.Sound.Rebuild.Spin")),
        new("Theme.Reflex.Rebuild", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QReflexCommand.QReflexCommandRenewal),

        new("Theme.Script.Character", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Caption", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Epoch", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Script.Gloss", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),

        new("Theme.Stem.Chip", QLookCue.QLookCueBase, null, ButtonBase.CommandProperty, QStemCommand.QStemCommandEntry),
        new("Theme.Stem.Chip", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Stem.Chip", QLookCue.QLookCueBase, "PStemCharacter",
            TextBlock.TextProperty, FrameworkElement.DataContextProperty),
        new("Theme.Stem.Chip", QLookCue.QLookCueBase, "PStemCharacter",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Stem.Chip", QLookCue.QLookCueHover, "PStemCharacter",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Diwei.Choice", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QDiweiCommand.QDiweiCommandSwitch),
        new("Theme.Diwei.Choice", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Diwei.Choice", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Diwei.Choice", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Diwei.Ipa", QLookCue.QLookCueBase, null, ButtonBase.CommandParameterProperty, false),
        new("Theme.Diwei.Respelling", QLookCue.QLookCueBase, null, ButtonBase.CommandParameterProperty, true),
        new("Theme.Diwei.Mark", QLookCue.QLookCueHover, "PTallyPart",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),
        new("Theme.Diwei.Mark", QLookCue.QLookCueChecked, "PTallyPart", TextBlock.ForegroundProperty, "Theme.Accent"),
        new("Theme.Diwei.Tally", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Diwei.Chip", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QDiweiCommand.QDiweiCommandEntry),
        new("Theme.Diwei.Chip", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Diwei.Chip", QLookCue.QLookCueBase, "PDiweiCharacter",
            TextBlock.TextProperty, FrameworkElement.DataContextProperty),
        new("Theme.Diwei.Chip", QLookCue.QLookCueBase, "PDiweiCharacter",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Diwei.Chip", QLookCue.QLookCueHover, "PDiweiCharacter",
            TextBlock.TextDecorationsProperty, TextDecorations.Underline),

        new("Theme.Fanqie.Character", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Knot", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Reading", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Label", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Text", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Link", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Link", QLookCue.QLookCueBase, "PFanqieSurface",
            Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Fanqie.Link", QLookCue.QLookCueBase, "PFanqieWord",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Fanqie.Link", QLookCue.QLookCueBase, "PFanqieWord",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Fanqie.Link", QLookCue.QLookCueHover, "PFanqieSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Fanqie.Link", QLookCue.QLookCuePress, "PFanqieSurface", UIElement.OpacityProperty, 0.72),
        new("Theme.Fanqie.Link", QLookCue.QLookCueEmpty, null, UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Fanqie.Initial", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QFanqieCommand.QFanqieCommandInitial),
        new("Theme.Fanqie.Rime", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QFanqieCommand.QFanqieCommandRime),
        new("Theme.Fanqie.StemKey", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QFanqieCommand.QFanqieCommandStem),
        new("Theme.Fanqie.StemKey", QLookCue.QLookCueBase, null,
            ContentControl.ContentProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueBase, null,
            ButtonBase.CommandProperty, QFanqieCommand.QFanqieCommandRepresentative),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueBase, null,
            ButtonBase.CommandParameterProperty, FrameworkElement.DataContextProperty),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueBase, "PFanqieStar",
            QIconImage.QIconSourceProperty, QIcon.QIconResolve("star", 14)),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueBase, "PFanqieOrder",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueHover, "PSurface", UIElement.OpacityProperty, 0.7),
        new("Theme.Fanqie.Representative", QLookCue.QLookCuePress, "PSurface", UIElement.OpacityProperty, 0.5),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueHover, "PFanqieStar", UIElement.OpacityProperty, 0.55),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueMarked, "PFanqieStar", UIElement.OpacityProperty, 1.0),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueMarked, "PFanqieOrder",
            UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueMarked, null,
            FrameworkElement.ToolTipProperty, "Display.FanqieRepresentativeMarked"),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueFaded, "PFanqieStar", UIElement.OpacityProperty, 1.0),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueFaded, "PFanqieOrder",
            UIElement.VisibilityProperty, Visibility.Visible),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueFaded, null,
            FrameworkElement.ToolTipProperty, "Display.FanqieRepresentativeMarked"),
        new("Theme.Fanqie.Representative", QLookCue.QLookCueFaded, null, UIElement.OpacityProperty, 0.62),

        new("Articulation.Glyph", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Articulation.Glyph", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Articulation.Glyph", QLookCue.QLookCuePress, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Articulation.Glyph", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Clip.Preview", QLookCue.QLookCueRefused, "PSurface", Border.BackgroundProperty, "Theme.Warning"),
        new("Theme.Clip.Preview", QLookCue.QLookCueRefused, null, Control.ForegroundProperty, "Theme.Surface"),
        new("Theme.Clip.Preview", QLookCue.QLookCueFetching, "PSurface", Border.BackgroundProperty, "Theme.Pending"),
        new("Theme.Clip.Preview", QLookCue.QLookCueFetching, null, Control.ForegroundProperty, "Theme.Surface"),
        new("Theme.Clip.Preview", QLookCue.QLookCuePlaying, "PSurface", Border.BackgroundProperty, "Theme.Accent"),
        new("Theme.Clip.Preview", QLookCue.QLookCuePlaying, null, Control.ForegroundProperty, "Theme.Surface"),
    ];
}
