using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;

namespace Llyn.UIDeportment;

internal static class QLookInput
{
    internal static readonly IReadOnlyList<QLook.QLookSetter> QLookInputState =
    [
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceButton",
            ToggleButton.IsCheckedProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceContent",
            ContentPresenter.ContentProperty, ComboBox.SelectionBoxItemProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PChoiceContent",
            ContentPresenter.ContentTemplateProperty, ComboBox.SelectionBoxItemTemplateProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PART_Popup",
            Popup.IsOpenProperty, ComboBox.IsDropDownOpenProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueBase, "PART_Popup",
            FrameworkElement.WidthProperty, FrameworkElement.ActualWidthProperty),
        new("Theme.Input.Choice", QLookCue.QLookCueHover, "PChoiceSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.Choice", QLookCue.QLookCueFocus, "PChoiceSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Input.Action", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Action", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Action", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Action", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.Action", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.Action", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Input.Pill", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Pill", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Pill", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Pill", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Pill", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.Pill", QLookCue.QLookCueDisabled, "PSurface", UIElement.OpacityProperty, 0.4),
        new("Theme.Input.Pill", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.Primary", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Primary", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Primary", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.Primary", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.AccentHover"),
        new("Theme.Input.Primary", QLookCue.QLookCuePress, "PSurface",
            Border.BackgroundProperty, "Theme.AccentPress"),
        new("Theme.Input.Primary", QLookCue.QLookCueDisabled, "PSurface", UIElement.OpacityProperty, 0.4),
        new("Theme.Input.Primary", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.Bin", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.Bin", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.Bin", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.Bin", QLookCue.QLookCueHover, "PSurface", Border.BackgroundProperty, "Theme.WarningSoft"),
        new("Theme.Input.Bin", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Warning"),
        new("Theme.Input.Bin", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Warning"),
        new("Theme.Input.Bin", QLookCue.QLookCuePress, "PSurface", Border.BackgroundProperty, "Theme.WarningSoft"),
        new("Theme.Input.Bin", QLookCue.QLookCuePress, "PSurface", Border.BorderBrushProperty, "Theme.WarningStrong"),
        new("Theme.Input.Bin", QLookCue.QLookCuePress, null, Control.ForegroundProperty, "Theme.WarningStrong"),
        new("Theme.Input.Bin", QLookCue.QLookCueDisabled, "PSurface", Border.BackgroundProperty, Brushes.Transparent),
        new("Theme.Input.Bin", QLookCue.QLookCueDisabled, "PSurface", Border.BorderBrushProperty, "Theme.DisabledLine"),
        new("Theme.Input.Bin", QLookCue.QLookCueDisabled, null, Control.ForegroundProperty, "Theme.DisabledInk"),
        new("Theme.Input.Bin", QLookCue.QLookCueDisabled, null, FrameworkElement.CursorProperty, Cursors.Arrow),

        new("Theme.Input.TogglePill", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.TogglePill", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.TogglePill", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.TogglePill", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.TogglePill", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Input.TogglePill", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.TogglePill", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.TogglePill", QLookCue.QLookCueChecked, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Input.ToggleAction", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueBase, "PSurfaceContent",
            FrameworkElement.HorizontalAlignmentProperty, Control.HorizontalContentAlignmentProperty),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Accent"),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Input.ToggleAction", QLookCue.QLookCueChecked, "PSurface",
            Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Input.Tab", QLookCue.QLookCueBase, "PSurface", Border.PaddingProperty, Control.PaddingProperty),
        new("Theme.Input.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Input.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Input.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Input.Tab", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Input.Tab", QLookCue.QLookCueHover | QLookCue.QLookCueIdle, "PSurface",
            Border.BackgroundProperty, "Theme.Surface"),
        new("Theme.Input.Tab", QLookCue.QLookCueHover | QLookCue.QLookCueIdle, null,
            Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Input.Tab", QLookCue.QLookCueSelected, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Search.Bar", QLookCue.QLookCueHover, null, Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Search.Bar", QLookCue.QLookCueFocus, null, Border.BorderBrushProperty, "Theme.Accent"),

        new("Theme.Search.Dropper", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Search.Dropper", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Search.Dropper", QLookCue.QLookCueHover, null, Control.ForegroundProperty, "Theme.Ink"),
        new("Theme.Search.Dropper", QLookCue.QLookCueChecked, "PSurface",
            Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Search.Dropper", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),

        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurface",
            Border.BackgroundProperty, Control.BackgroundProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurface",
            Border.BorderBrushProperty, Control.BorderBrushProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurface",
            Border.BorderThicknessProperty, Control.BorderThicknessProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceStack",
            FrameworkElement.MarginProperty, Control.PaddingProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceMark",
            QIconImage.QIconSourceProperty, QLook.QLookIconProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontSizeProperty, Control.FontSizeProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.FontWeightProperty, Control.FontWeightProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.ForegroundProperty, Control.ForegroundProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBase, "PSurfaceLabel",
            TextBlock.TextProperty, ContentControl.ContentProperty),
        new("Theme.Search.Helper", QLookCue.QLookCueBare, "PSurfaceMark",
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Search.Helper", QLookCue.QLookCueMute, "PSurfaceLabel",
            UIElement.VisibilityProperty, Visibility.Collapsed),
        new("Theme.Search.Helper", QLookCue.QLookCueMute, "PSurfaceMark",
            FrameworkElement.MarginProperty, "Theme.Search.Helper.MarkInset"),
        new("Theme.Search.Helper", QLookCue.QLookCueMute, null,
            Control.PaddingProperty, "Theme.Search.Helper.MuteInset"),
        new("Theme.Search.Helper", QLookCue.QLookCueHover, "PSurface",
            Border.BackgroundProperty, "Theme.SurfaceRaised"),
        new("Theme.Search.Helper", QLookCue.QLookCueHover, "PSurface", Border.BorderBrushProperty, "Theme.Line"),
        new("Theme.Search.Helper", QLookCue.QLookCueChecked, "PSurface", Border.BackgroundProperty, "Theme.AccentSoft"),
        new("Theme.Search.Helper", QLookCue.QLookCueChecked, "PSurface",
            Border.BorderBrushProperty, "Theme.AccentEdge"),
        new("Theme.Search.Helper", QLookCue.QLookCueChecked, null, Control.ForegroundProperty, "Theme.Accent"),
        new("Theme.Search.Helper", QLookCue.QLookCueChecked, null, Control.FontWeightProperty, FontWeights.SemiBold),
    ];
}
